name: Manual Build (Win/Linux)

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read # Read permissions needed to checkout code

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main # Explicitly checkout main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Specify your Node.js version - using LTS as an example
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        # Run electron-builder directly to build for the OS runner
        # It will use the config in package.json (win portable, linux AppImage)
        run: npx electron-builder --publish never

      - name: Upload Windows Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: booklet-tool-windows-portable
          path: dist/*.exe
          retention-days: 7 # Optional: How long to keep the artifact

      - name: Upload Linux Artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: booklet-tool-linux-appimage
          path: dist/*.AppImage
          retention-days: 7 # Optional: How long to keep the artifact 